/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatIndexRouteImport } from './routes/$/index'
import { Route as SearchCollectionRouteImport } from './routes/search/$collection'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatIndexRoute = SplatIndexRouteImport.update({
  id: '/$/',
  path: '/$/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchCollectionRoute = SearchCollectionRouteImport.update({
  id: '/search/$collection',
  path: '/search/$collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/search/$collection': typeof SearchCollectionRoute
  '/$': typeof SplatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/search/$collection': typeof SearchCollectionRoute
  '/$': typeof SplatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/search/$collection': typeof SearchCollectionRoute
  '/$/': typeof SplatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/product/$productId' | '/search/$collection' | '/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/product/$productId' | '/search/$collection' | '/$'
  id: '__root__' | '/' | '/product/$productId' | '/search/$collection' | '/$/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  SearchCollectionRoute: typeof SearchCollectionRoute
  SplatIndexRoute: typeof SplatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$/': {
      id: '/$/'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$collection': {
      id: '/search/$collection'
      path: '/search/$collection'
      fullPath: '/search/$collection'
      preLoaderRoute: typeof SearchCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  SearchCollectionRoute: SearchCollectionRoute,
  SplatIndexRoute: SplatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
